---
spring:
  application:
    name: amisoft-service-welcome   # This should be the same name of property file in Git.

server:
  port: 9001

amisoft:
  attendee-service:
    uri: http://localhost:8003

